<?php $gd_id = $gd ? intval($gd->gd_id) : 0; ?>
<?php $loai = $gd ? $gd->loai_phieu : $default_loai; ?>
<form id="tc-thu-chi-form" class="tc-thu-chi-form tc-module-form tc-bootstrap-form" method="post" data-action="<?php print check_plain(url('thu-chi/ajax-save')); ?>">
  <input type="hidden" name="gd_id" value="<?php print intval($gd_id); ?>">
  <input type="hidden" name="nhom_giao_dich" value="khac">
  <div class="tc-form-alert d-none"></div>

  <div class="card mb-3 tc-form-section"><div class="card-body">
    <div class="row g-3 align-items-end">
      <div class="col-2"><label class="form-label">Loại phiếu <span class="text-danger">*</span></label><select name="loai_phieu" class="form-select tc-loai-phieu" required><?php foreach (thu_chi_loai_options() as $key => $label): ?><option value="<?php print check_plain($key); ?>"<?php print $loai === $key ? ' selected' : ''; ?>><?php print check_plain($label); ?></option><?php endforeach; ?></select></div>
      <div class="col-4"><label class="form-label">Phân loại phiếu <span class="text-danger">*</span></label><select name="loai_giao_dich[]" class="form-select tc-category-select2" multiple data-placeholder="Chọn hoặc nhập mới phân loại" data-ajax-url="<?php print check_plain(url('thu-chi/ajax-category-search')); ?>" required><?php foreach (thu_chi_selected_danh_muc_options($selected_categories, 'Phân loại thu chi') as $key => $label): ?><option value="<?php print intval($key); ?>" selected><?php print check_plain($label); ?></option><?php endforeach; ?></select></div>
      <div class="col-2"><label class="form-label">Quỹ <span class="text-danger">*</span></label><select name="nid_quy" class="form-select tc-select2-basic" required><option value="0">Chọn quỹ</option><?php $quy_value = $gd ? intval($gd->nid_quy) : 0; foreach (thu_chi_quy_options(TRUE) as $key => $label): ?><option value="<?php print intval($key); ?>"<?php print $quy_value === intval($key) ? ' selected' : ''; ?>><?php print check_plain($label); ?></option><?php endforeach; ?></select></div>
      <div class="col-2"><label class="form-label">Ngày phiếu <span class="text-danger">*</span></label><input type="text" name="ngay_giao_dich" class="form-control tc-flatpickr-date" value="<?php print check_plain($ngay); ?>" required><input type="hidden" name="thang_luong" value="<?php print check_plain($thang); ?>"></div>
      <div class="col-2"><label class="form-label">Người đề xuất <span class="text-danger">*</span></label><select name="uid_nguoi_de_xuat" class="form-select tc-select2-basic" required><option value="0">Chọn</option><?php foreach (thu_chi_user_options() as $uid => $label): ?><option value="<?php print intval($uid); ?>"<?php print $nguoi_de_xuat_value === intval($uid) ? ' selected' : ''; ?>><?php print check_plain($label); ?></option><?php endforeach; ?></select></div>
    </div>
    <div class="row g-3 align-items-end mt-1">
      <div class="col-4"><label class="form-label">Khách hàng</label><select name="nid_khach_hang" class="form-select tc-select2-basic"><option value="0">Không chọn</option><?php $khach_hang_value = $gd ? intval($gd->nid_khach_hang) : 0; foreach (thu_chi_khach_hang_options() as $key => $label): ?><option value="<?php print intval($key); ?>"<?php print $khach_hang_value === intval($key) ? ' selected' : ''; ?>><?php print check_plain($label); ?></option><?php endforeach; ?></select></div>
      <div class="col-4"><label class="form-label">Nhà cung cấp</label><select name="nid_nha_cung_cap" class="form-select tc-select2-basic"><option value="0">Không chọn</option><?php $ncc_value = $gd ? intval($gd->nid_nha_cung_cap) : 0; foreach (thu_chi_nha_cung_cap_options() as $key => $label): ?><option value="<?php print intval($key); ?>"<?php print $ncc_value === intval($key) ? ' selected' : ''; ?>><?php print check_plain($label); ?></option><?php endforeach; ?></select></div>
      <div class="col-4"><label class="form-label">Chuyến xe</label><select name="nid_chuyen_xe" class="form-select tc-select2-basic"><option value="0">Không chọn</option><?php $cx_value = $gd ? intval($gd->nid_chuyen_xe) : 0; foreach (thu_chi_chuyen_xe_options() as $key => $label): ?><option value="<?php print intval($key); ?>"<?php print $cx_value === intval($key) ? ' selected' : ''; ?>><?php print check_plain($label); ?></option><?php endforeach; ?></select></div>
    </div>
  </div></div>

  <div class="card mt-3 tc-detail-card"><div class="card-header d-flex justify-content-between align-items-center py-2"><div><strong>Chi tiết phiếu</strong></div><button type="button" class="btn btn-label-primary btn-sm tc-add-detail-row"><i class="icon-base ti tabler-plus me-1"></i>Thêm dòng</button></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-bordered align-middle mb-0 tc-detail-table"><thead><tr><th class="tc-detail-content-col">Nội dung</th><th class="text-end tc-detail-money-col">Đơn giá</th><th class="text-end tc-detail-qty-col">Số lượng</th><th class="tc-detail-unit-col">ĐVT</th><th class="text-end tc-detail-money-col">Tổng tiền</th><th class="text-end tc-detail-vat-col">VAT (%)</th><th class="text-end tc-detail-money-col">Thành tiền</th><th class="text-center tc-detail-remove-col">Xóa</th></tr></thead><tbody class="tc-detail-body" data-next-index="<?php print count($chi_tiet); ?>"><?php foreach ($chi_tiet as $index => $detail) { print thu_chi_render_detail_row($detail, $index); } ?></tbody></table></div></div><div class="card-footer d-flex justify-content-end align-items-center gap-2 py-2"><label class="mb-0 fw-semibold">Tổng tiền phiếu</label><input type="text" name="so_tien" class="form-control form-control-sm tc-money-input tc-grand-total text-end" value="<?php print check_plain($gd ? thu_chi_format_money($gd->so_tien) : '0'); ?>" readonly></div></div>
  <script type="text/template" id="tc-detail-row-template"><?php print str_replace('</script>', '<\/script>', thu_chi_render_detail_row(array(), '__INDEX__')); ?></script>
  <div class="d-flex justify-content-end gap-2 mt-4 tc-modal-actions"><button type="button" class="btn btn-label-secondary btn-sm" data-bs-dismiss="modal">Đóng</button><button type="submit" class="btn btn-primary btn-sm tc-btn-save-thu-chi"><span class="spinner-border spinner-border-sm me-1 tc-btn-spinner d-none" role="status" aria-hidden="true"></span><span class="tc-btn-text"><i class="icon-base ti tabler-device-floppy me-1"></i><?php print $gd_id ? 'Cập nhật phiếu' : 'Lưu phiếu'; ?></span></button></div>
</form>
