<?php

function hop_dong_schema() {
  $schema['hop_dong'] = array(
    'description' => 'Hợp đồng.',
    'fields' => array(
      'nid' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'so_hop_dong' => array(
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),
      'ngay_hop_dong' => array(
        'type' => 'varchar',
        'length' => 10,
        'not null' => FALSE,
      ),
      'han_hop_dong' => array(
        'type' => 'varchar',
        'length' => 10,
        'not null' => FALSE,
      ),
      'khach_hang' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ),
      'files' => array(
        'type' => 'text',
        'size' => 'big',
        'not null' => FALSE,
      ),
      'ghi_chu' => array(
        'type' => 'text',
        'not null' => FALSE,
      ),
      'hoat_dong' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 1,
      ),
      'created' => array(
        'type' => 'varchar',
        'length' => 19,
        'not null' => FALSE,
      ),
      'changed' => array(
        'type' => 'varchar',
        'length' => 19,
        'not null' => FALSE,
      ),
    ),
    'primary key' => array('nid'),
    'indexes' => array(
      'hoat_dong' => array('hoat_dong'),
      'so_hop_dong' => array('so_hop_dong'),
      'khach_hang' => array('khach_hang'),
    ),
  );

  return $schema;
}

function hop_dong_update_7001() {
  drupal_install_schema('hop_dong');
}

function hop_dong_update_7002() {
  db_add_field('hop_dong', 'files', array(
    'type' => 'text',
    'size' => 'big',
    'not null' => FALSE,
  ));
}
