<?php

function khach_hang_schema() {
  $schema['khach_hang'] = array(
    'description' => 'Khách hàng (Doanh nghiệp, Cá nhân, NCC, Đối tác, Khác).',
    'fields' => array(
      'nid' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'ten' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ),
      'ma_kh' => array(
        'type' => 'varchar',
        'length' => 50,
        'not null' => FALSE,
      ),
      'phan_loai' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ),
      'cccd_mst' => array(
        'type' => 'varchar',
        'length' => 50,
        'not null' => FALSE,
      ),
      'sdt' => array(
        'type' => 'varchar',
        'length' => 20,
        'not null' => FALSE,
      ),
      'dia_chi' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
      ),
      'thong_tin_ngan_hang' => array(
        'type' => 'text',
        'not null' => FALSE,
      ),
      'nv_kinh_doanh' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ),
      'dob' => array(
        'type' => 'varchar',
        'length' => 10,
        'not null' => FALSE,
      ),
      'ghi_chu' => array(
        'type' => 'text',
        'not null' => FALSE,
      ),
      'hoat_dong' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 1,
      ),
      'created' => array(
        'type' => 'varchar',
        'length' => 19,
        'not null' => FALSE,
      ),
      'changed' => array(
        'type' => 'varchar',
        'length' => 19,
        'not null' => FALSE,
      ),
    ),
    'primary key' => array('nid'),
    'indexes' => array(
      'hoat_dong' => array('hoat_dong'),
      'phan_loai' => array('phan_loai'),
      'nv_kinh_doanh' => array('nv_kinh_doanh'),
    ),
  );

  return $schema;
}

function khach_hang_update_7001() {
  drupal_install_schema('khach_hang');
}