<?php

function danh_muc_schema() {
  $schema['danh_muc'] = array(
    'description' => 'Danh mục (Phòng ban, Chức vụ, Địa điểm, Chi phí).',
    'fields' => array(
      'nid' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'ten' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ),
      'phan_loai' => array(
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),
      'hoat_dong' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 1,
      ),
      'created' => array(
        'type' => 'varchar',
        'length' => 19,
        'not null' => FALSE,
      ),
      'changed' => array(
        'type' => 'varchar',
        'length' => 19,
        'not null' => FALSE,
      ),
    ),
    'primary key' => array('nid'),
    'indexes' => array(
      'hoat_dong' => array('hoat_dong'),
      'phan_loai' => array('phan_loai'),
    ),
  );

  return $schema;
}

function danh_muc_update_7001() {
  drupal_install_schema('danh_muc');
}