<?php

/**
 * @file
 * Schema cho bang phuong_tien_mooc.
 */

function phuong_tien_mooc_schema() {
  $schema['phuong_tien_mooc'] = array(
    'description' => 'Bang quan he dau keo - mooc.',
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'nid_dau_keo' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'nid_mooc' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'hoat_dong' => array(
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 1,
      ),
      'created' => array(
        'type' => 'varchar',
        'length' => 19,
        'not null' => TRUE,
        'default' => '',
      ),
      'changed' => array(
        'type' => 'varchar',
        'length' => 19,
        'not null' => TRUE,
        'default' => '',
      ),
    ),
    'primary key' => array('id'),
    'indexes' => array(
      'hoat_dong' => array('hoat_dong'),
      'nid_dau_keo' => array('nid_dau_keo'),
      'nid_mooc' => array('nid_mooc'),
    ),
  );

  return $schema;
}
